apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
  labels:
    app.kubernetes.io/name: root-application
spec:
  project: default
  source:
    repoURL: https://github.com/minhajul/kube-sandbox.git
    targetRevision: HEAD
    path: infrastructure/charts/kube-sandbox
    helm:
      releaseName: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps/v1
      kind: Deployment
      jsonPointers:
        - /spec/replicas   # HPA writes this; we don't use HPA yet but it's harmless
        - /metadata/generation
        - /status
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /spec/ports/0/nodePort
        - /spec/ipFamilies
        - /spec/ipFamilyPolicy
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /status
    - group: ""
      kind: Endpoints
      jsonPointers:
        - /subsets
