{{- if .Values.ingress.enabled -}}
{{- $ctx := . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kube-sandbox.fullname" $ctx }}
  labels:
    {{- include "kube-sandbox.labels" $ctx | nindent 4 }}
  {{- with $ctx.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $ctx.Values.ingress.className }}
  rules:
  {{- range $ctx.Values.ingress.hosts }}
    {{- $host := .host }}
    {{- range .paths }}
    - {{ if $host }}host: {{ $host | quote }}
      {{ end }}http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "kube-sandbox.appFullname" (dict "ctx" $ctx "appName" .service) }}
                port:
                  number: {{ .port }}
    {{- end }}
  {{- end }}
{{- end }}
